# Generated by Django 5.2.17 on 2026-09-27 13:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Usa un ISBN de 10 o 13 caracteres, sin espacios ni guiones.', regex='\\A(?:[0-9]{9}[0-9X]|[0-9]{13})\\Z')])),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('supplier_country', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Usa un código de país de dos letras mayúsculas, como ES.', regex='\\A[A-Z]{2}\\Z')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost_usd__gt', 0)), name='book_cost_usd_positive'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='book_stock_nonnegative'), models.CheckConstraint(condition=models.Q(('selling_price_local__isnull', True), ('selling_price_local__gte', 0), _connector='OR'), name='book_selling_price_nonnegative')],
            },
        ),
    ]
