# Generated by Django 5.2.17 on 2026-09-27 14:07

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[books.validators.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='book',
            name='supplier_country',
            field=models.CharField(max_length=2, validators=[books.validators.validate_country]),
        ),
    ]
