# Generated by Django 5.2.17 on 2026-09-27 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateQuote',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=16, max_digits=30)),
                ('provider_updated_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField()),
                ('next_update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RateSyncState',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('lease_until', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(null=True)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
